### ISSUE TITLE
[b] termcolor not found

### ISSUE THREAD

**Issue by hieueastagile** [EastAgile/robber.py#47]
```
======================================================================
ERROR: Failure: ImportError (No module named termcolor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.11/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/ubuntu/virtualenvs/venv-2.7.11/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/ubuntu/virtualenvs/venv-2.7.11/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/ubuntu/CPDBv2_backend/cpdb/analytics/tests/test_serializers.py", line 3, in <module>
    from robber import expect
  File "/home/ubuntu/virtualenvs/venv-2.7.11/src/robber/robber/__init__.py", line 7, in <module>
    import robber.matchers  # noqa F401
  File "/home/ubuntu/virtualenvs/venv-2.7.11/src/robber/robber/matchers/__init__.py", line 21, in <module>
    from robber.matchers.boolean import *  # noqa F403
  File "/home/ubuntu/virtualenvs/venv-2.7.11/src/robber/robber/matchers/boolean.py", line 3, in <module>
    from robber.matchers.base import Base
  File "/home/ubuntu/virtualenvs/venv-2.7.11/src/robber/robber/matchers/base.py", line 1, in <module>
    from termcolor import colored
ImportError: No module named termcolor
```

**Comment by catriuspham** [comment]
@oyster Please close this issue also
